import test from 'node:test';
import assert from 'node:assert/strict';
import { readFile } from 'node:fs/promises';
import path from 'node:path';
import { loadConfig,validateConfig,sourceDecision,ROOT } from '../src/config.ts';
import { cents,canonical,safeURL,shift } from '../src/util.ts';
import { gate,assess,rank,score } from '../src/gates.ts';
import { measureFlood,polygonArea } from '../src/flood.ts';
import { classifyAnswer } from '../src/model.ts';
import { MemoryStore } from '../src/store.ts';
import { mailPaused,contactDue,allowedContact,renderTemplate } from '../src/mail.ts';
import type { Evidence,Row } from '../src/types.ts';
const cfg=await loadConfig();const b=cfg.business;const now='2026-09-16T10:00:00.000Z';
const e=(fact:string,value:any,extra:Row={}):Evidence=>({id:'e-'+fact,site_id:'s',fact,value,source_url:'fixture://official/'+fact,fetched_at:now,expires_at:shift(now,7),method:fact==='zoning'?'official_layer_and_use_table':'written_quote',source_kind:'official',synthetic:true,scope:'office',...extra});
const zoning={status:'permitted',official:true,section:'Test UDO 1',layer_url:'fixture://layer',use_table_url:'fixture://udo'};
const flood={centroid_zone:'X',high_risk_fraction:0,coverage_complete:true,geometry_checked:true};
const site={id:'s',available:true,office:{enclosed:true,sqft:120,separate_entrance:true},display_count:2,signage_available:true,records_storage:true,public_contact_hours:true,shared:false,sublease_consent:true,drive:{minutes:30,inside_isochrone:true}};
test('business defaults match approved task',()=>{assert.equal(b.rent.min_monthly,600);assert.equal(b.rent.max_monthly,1000);assert.equal(b.site.min_vehicle_display,2);assert.equal(b.mail.followup_days,5);assert.equal(b.mail.max_followups,2);assert.equal(cfg.providers.paid_enabled,false);});
for(const [name,mutate] of [
 ['inverted rent',(x:any)=>x.business.rent.min_monthly=1001],['bad shared policy',(x:any)=>x.business.site.shared_lot='primary'],['priority weights',(x:any)=>x.business.ranking.weights.competitors=1],['invalid zone',(x:any)=>x.business.schedule.timezone='bad/timezone'],['unheld license',(x:any)=>x.business.dealer.license_status='missing'],['duplicate source',(x:any)=>x.sources.sources.push(x.sources.sources[0])],['zero followup interval',(x:any)=>x.business.mail.followup_days=0]
] as const)test('reject '+name,()=>{const x=structuredClone(cfg);mutate(x);assert.throws(()=>validateConfig(x));});
for(const status of ['prohibited','unclear'])test('source terms '+status+' blocked even if enabled',()=>assert.equal(sourceDecision({enabled:true,terms_status:status,robots_txt:'allowed'}).allowed,false));
for(const robots of ['disallowed','unknown'])test('source robots '+robots+' blocked',()=>assert.equal(sourceDecision({enabled:true,terms_status:'allowed',robots_txt:robots}).allowed,false));
test('explicit allowed source passes',()=>assert.equal(sourceDecision({enabled:true,terms_status:'allowed',robots_txt:'allowed'}).allowed,true));
test('disabled source stays disabled',()=>assert.equal(sourceDecision({enabled:false,terms_status:'allowed',robots_txt:'allowed'}).allowed,false));
for(const amount of [600,800,1000])test('rent accepts inclusive amount '+amount,()=>assert.equal(gate('rent',e('rent',{monthly:amount,currency:'USD',written:true}),b,now).status,'PASS'));
for(const amount of [599.99,1000.01])test('rent rejects hard bound breach '+amount,()=>assert.equal(gate('rent',e('rent',{monthly:amount,currency:'USD',written:true}),b,now).status,'FAIL'));
for(const value of [{monthly:null,written:true,currency:'USD'},{monthly:800,written:false,currency:'USD'},{monthly:800,written:true,currency:'EUR'}])test('rent incomplete or unsupported quote stays unknown '+JSON.stringify(value),()=>assert.equal(gate('rent',e('rent',value),b,now).status,'UNKNOWN'));
test('decimal parser is not floating coercion',()=>{assert.equal(cents('600.01'),60001);assert.equal(cents('6e2'),null);assert.equal(cents(-1),null);});
test('expired evidence is never a soft pass',()=>assert.equal(gate('rent',e('rent',{monthly:800,currency:'USD',written:true},{expires_at:now}),b,now).status,'UNKNOWN'));
test('future evidence rejected',()=>assert.equal(gate('zoning',e('zoning',zoning,{fetched_at:shift(now,1)}),b,now).status,'UNKNOWN'));
test('zoning requires exact section',()=>assert.equal(gate('zoning',e('zoning',{...zoning,section:null}),b,now).status,'UNKNOWN'));
test('zoning layer alone insufficient',()=>assert.equal(gate('zoning',e('zoning',{...zoning,use_table_url:null}),b,now).status,'UNKNOWN'));
test('broker opinion cannot approve zoning',()=>assert.equal(gate('zoning',e('zoning',zoning,{method:'broker_opinion'}),b,now).status,'UNKNOWN'));
test('verified conditional use passes',()=>assert.equal(gate('zoning',e('zoning',{...zoning,status:'conditional',conditional_verified:true}),b,now).status,'PASS'));
test('unverified conditional use stays pending',()=>assert.equal(gate('zoning',e('zoning',{...zoning,status:'conditional',conditional_verified:false}),b,now).status,'UNKNOWN'));
for(const zone of b.flood.high_risk_zones)test('high risk centroid '+zone+' fails',()=>assert.equal(gate('flood',e('flood',{...flood,centroid_zone:zone}),b,now).status,'FAIL'));
test('half high-risk area is not majority outside',()=>assert.equal(gate('flood',e('flood',{...flood,high_risk_fraction:.5}),b,now).status,'FAIL'));
test('missing flood coverage stays unknown',()=>assert.equal(gate('flood',e('flood',{...flood,coverage_complete:false}),b,now).status,'UNKNOWN'));
test('shaded X is warn only',()=>assert.equal(gate('flood',e('flood',{...flood,centroid_zone:'X_SHADED'}),b,now).status,'PASS'));
const evidence=[e('rent',{monthly:800,currency:'USD',written:true}),e('zoning',zoning),e('flood',flood)];
test('three gates and premises checks produce viable site',()=>assert.equal(assess(site,evidence,b,now).viable,true));
test('contradictory contemporaneous written quotes stay pending',()=>{const conflict=e('rent',{monthly:950,currency:'USD',written:true},{id:'other-quote',source_url:'fixture://second-quote'});const a=assess(site,[...evidence,conflict],b,now);assert.equal(a.viable,false);assert.equal(a.gates.rent.status,'UNKNOWN');});
for(const [name,patch]of [['office',{office:{enclosed:false}}],['display',{display_count:1}],['drive',{drive:{minutes:61,inside_isochrone:false}}],['sign',{signage_available:false}],['sublease',{shared:true,sublease_consent:false}]] as const)test('premises '+name+' blocks',()=>assert.equal(assess({...site,...patch},evidence,b,now).viable,false));
test('shared always sorts after every standalone regardless of score',()=>{const sorted=rank([{id:'shared',shared:true,viable:true,score:{total:100}},{id:'solo',shared:false,viable:true,score:{total:1}}]);assert.equal(sorted[0].id,'solo');});
test('scores are deterministic with visible components',()=>{const s=score({...site,current_rent:800,traffic:{aadt:20000},imagery:{frontage_m:50,corner:true,line_of_sight:.8},competitors:{count:2}},b);assert.ok(s.total>=0&&s.total<=100);assert.equal(Object.keys(s.components).length,5);});
test('address normalization does not collapse suites',()=>{assert.equal(canonical('1 Test Street'),'1 test st');assert.notEqual(canonical('Suite A'),canonical('Suite B'));});
const rectangle=(x1:number,y1:number,x2:number,y2:number)=>[[x1,y1],[x2,y1],[x2,y2],[x1,y2],[x1,y1]];
test('flood geometry measures safe full coverage',()=>{const ring=rectangle(-77.37,35.61,-77.36,35.62);const m=measureFlood({geometry:{type:'Polygon',coordinates:[ring]},centroid:[-77.365,35.615]},[{geometry:{rings:[ring]},attributes:{FLD_ZONE:'X'}}],['AE']);assert.equal(m.coverage_complete,true);assert.equal(m.high_risk_fraction,0);assert.equal(m.centroid_zone,'X');});
test('flood geometry refuses missing coverage',()=>assert.equal(measureFlood({geometry:{type:'Polygon',coordinates:[rectangle(0,0,1,1)]},centroid:[.5,.5]},[],['AE']).coverage_complete,false));
test('polygon area oracle',()=>assert.equal(polygonArea(rectangle(0,0,2,3)),6));
test('unsafe source URLs denied',()=>{for(const u of ['file:///etc/passwd','http://127.0.0.1/a','http://169.254.169.254/','https://user:secret@example.com'])assert.throws(()=>safeURL(u));});
test('unverified or malformed recipients denied',()=>{assert.equal(allowedContact('a@example.invalid','fixture://listing','leasing',true),true);assert.equal(allowedContact('a\r\nBcc:x@example.invalid','fixture://listing','leasing',true),false);assert.equal(allowedContact('a@example.com','','leasing',false),false);});
test('template never exposes maximum budget or adds a new ask',()=>{const text=renderTemplate('rent',{address:'Fixture address',suite:'A'});assert.ok(!text.includes('1000'));assert.throws(()=>renderTemplate('offer',{}));});
test('exact sender stop marks do-not-contact',()=>assert.equal(classifyAnswer({from:'a@example.invalid',fact:'rent',body:'STOP'},{recipient:'a@example.invalid',fact:'rent'}).stop,true));
test('spoofed sender cannot resolve or suppress case',()=>assert.equal(classifyAnswer({from:'other@example.invalid',fact:'rent',body:'STOP'},{recipient:'a@example.invalid',fact:'rent'}).accepted,false));
test('no response and autoreply are not approvals',()=>assert.equal(classifyAnswer({from:'a@example.invalid',fact:'rent',autoreply:true},{recipient:'a@example.invalid',fact:'rent'}).accepted,false));
test('recipient cooldown applies across cases at one site',()=>{const s=new MemoryStore();s.put('messages',{id:'m',site_id:'s',recipient:'a@example.invalid',direction:'outbound',created_at:now});assert.equal(contactDue(s,site,'a@example.invalid',now,5),false);assert.equal(contactDue(s,site,'a@example.invalid',shift(now,5),5),true);});
test('24h bounce threshold auto-pauses all sending',()=>{const s=new MemoryStore();s.put('messages',{id:'m',direction:'outbound',status:'bounced',created_at:now});assert.ok(mailPaused(s,b.mail,now));assert.equal(s.state.controls.sending_paused,true);});
test('all example environment values are empty',async()=>{const env=await readFile(path.join(ROOT,'.env.example'),'utf8');for(const line of env.split('\n').filter(x=>x&&!x.startsWith('#')))assert.match(line,/^[A-Z][A-Z0-9_]*=$/);});
