import http from 'node:http';
import https from 'node:https';
import net from 'node:net';
import tls from 'node:tls';
import dgram from 'node:dgram';
import { syncBuiltinESMExports } from 'node:module';
const deny=()=>{throw new Error('TEST_NETWORK_DISABLED');};
globalThis.fetch=deny;globalThis.WebSocket=deny;
http.request=deny;http.get=deny;https.request=deny;https.get=deny;
net.connect=deny;net.createConnection=deny;net.Socket.prototype.connect=deny;tls.connect=deny;dgram.createSocket=deny;
syncBuiltinESMExports();
