import type { AppConfig,Row,Store,Evidence } from './types.ts';
import { Registry } from './providers/index.ts';
import { assess,rank,current } from './gates.ts';
export function createReport(store:Store,config:AppConfig,registry:Registry,now:string,run:Row):Row {
 const evidence=store.all('evidence') as Evidence[];const assessed=store.all('sites').map(s=>({...s,...assess(s,evidence,config.business,now)}));
 const ordered=rank(assessed);const ranking=new Map(ordered.map((s,i)=>[s.id,i+1]));
 const p=config.providers.selections;
 const sites=assessed.map(s=>({site_id:s.id,parcel_id:s.parcel_id??null,listing_ids:store.all('listings').filter(l=>l.site_id===s.id).map(l=>l.id),address:s.address,in_search_area:s.drive?.inside_isochrone===true,drive_minutes:s.drive?.minutes??null,shared_lot:!!s.shared,gates:Object.fromEntries(Object.entries(s.gates).map(([fact,g]:any)=>[fact,{status:g.status==='UNKNOWN'?'pending':g.status.toLowerCase(),evidence_ids:g.evidence_id?[g.evidence_id]:[]}])),viable:s.viable,score:(s.score?.total??0)/100,rank:ranking.get(s.id)??null,metrics:{aadt:s.traffic?.aadt??null,visibility:s.score?.components?.visibility??null,drive_minutes:s.drive?.minutes??null,rent_monthly:s.current_rent??null,competitors:s.competitors?.count??null},open_cases:store.all('cases').filter(c=>c.site_id===s.id&&c.status!=='resolved').map(c=>({case_type:['rent','zoning'].includes(c.fact)?c.fact:'space',status:c.status,recipient:c.recipient})),lat:s.geo?.lat??null,lon:s.geo?.lon??null,street_photo:s.imagery?.image_url??'/fixture-site.svg',aerial_thumbnail:s.imagery?.image_url??'/fixture-site.svg',score_breakdown:s.score?.weighted??{},warnings:s.warnings,blockers:s.blockers,stage:s.stage,synthetic:s.synthetic,suite:s.suite}));
 return {report:{run_id:run.id,run_date:now,offline:registry.offline||sites.every(s=>s.synthetic),providers:{paid_enabled:config.providers.paid_enabled,geocoder:p.geocoding,parcels:p.parcels,drivetime:p.drive_time,imagery:p.imagery,poi:p.competitors,crawler:p.crawling,tiles:p.map_tiles},sites,evidence:evidence.map(e=>({evidence_id:e.id,site_id:e.site_id,fact:e.fact,value:e.value,source_url:e.source_url,fetched_at:e.fetched_at,expires_at:e.expires_at,method:e.method,synthetic:e.synthetic})),external_calls:registry.transport.calls},messages:store.all('messages').filter(m=>m.direction==='outbound'&&m.status==='sent'&&m.run_id===run.id).map(m=>({site_id:m.site_id,case_type:store.all('cases').find(c=>c.id===m.case_id)?.fact,to:m.recipient,subject:'DealerSource verification '+m.case_id,sent_at:m.created_at,template_id:store.all('cases').find(c=>c.id===m.case_id)?.fact})),run:{run_id:run.id,run_date:now,started_at:run.started_at,finished_at:run.finished_at??now,counts:{...run.counts,viable:ordered.length},errors:run.errors},ui:{sources:store.all('sources'),cases:store.all('cases'),controls:config.business.mail.paused?{...store.state.controls,sending_paused:true,pause_reason:'Paused in configuration'}:store.state.controls,business:config.business,provider_status:registry.status(),expired:evidence.filter(e=>!current(e,now)).map(e=>e.id),dropped:[]}};
}
